config/routes.rb
Rails.application.routes.draw do

root 'products#index'
resources :products
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create, :destroy]
resources :carts
get '/login', to: 'sessions#new'
get '/products', to: 'products#index'
get '/carts', to: 'carts#index'
post '/add_item/:product_id', to: 'carts#add_item'
post '/remove_item/:cart_id', to: 'carts#remove_item'
post '/purchase/:order_id', to: 'carts#purchase'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carts
  has_many :products, through: :carts
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :carts
    has_many :orders, through: :cart
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

helper_method :current_user
helper_method :active_order

def current_user 
  @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
end

  def authorize
    redirect_to login_path, alert: 'Not authorized - you must be logged in' if current_user.nil?
  end

  def active_order
    @active_order = current_user.orders.find_by(is_active: true)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authorize

    def index
         @carts = Cart.where(order_id: active_order.id)
    end

    def show
    end

    def new
        @cart = Cart.new
    end
    
    def add_item
        @current_cart_item = Cart.find_by(order_id: active_order.id, product_id: params[:product_id])
        if @current_cart_item.nil?

            @cart = Cart.new(order_id: active_order.id, product_id: params[:product_id], quantity: params[:quantity])
            if @cart.save
            redirect_to products_path
            else 
            redirect_to products_path #to do send back message like cart add unsuccessful
            end
        else 
          if @current_cart_item.update_attributes(quantity: params[:quantity])
            redirect_to products_path
          else
            flash[:notice] = 'Update Not Successful'
    end
end
end

    def remove_item
        Cart.find(params[:cart_id]).destroy
        redirect_to products_path
    end

    def purchase
        current_user.orders.update(is_active: false)
        current_user.orders << Order.new(is_active: true)
        #direct to somewhere else
        redirect_to products_path
    end

    def create
        @current_order = Order.find_by(is_active: true)
        @cart = Cart.new(cart_params)
        if @cart.save
            redirect_to products_path
        else
            render :new 
        end
    end
    private
        def cart_params
        params.require(:cart).permit(:product_id)
        end

    
end

app/controllers/order_controller.rb
class OrderController < ApplicationController 

    before_action :set_cart, only: [:create, :destroy]

    def index 
        @orders = User.find(current_user.id).orders
    end
    
    def create
        @cart.add_product(params)

        if @cart.save
            redirect_to cart_path
        else
            flash[:error] = "There was a problem adding this to your cart."
            redirect_to @add_product
        end
    end

def destroy
    @cart_item.destroy
    redirect_to cart_path
end

private

def set_cart_item
    @cart_item = CartItem.find(params[:id])
end

def cart_item_params
    params.require(:cart_item).permit(:product_id, :cart_id, :quantity)
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    # before_action :set_ho, only: [:show, :edit, :update, :destroy]
    # before_action :authorize, except: [:index, :show]

    def index
        if current_user.nil? 
            redirect_to new_session_path
        else
            @products = Product.all
        end
    end

    def show
        @product = Product.find(params[:id])
        @order = Order.new
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to products_path, notice: 'logged in'
        else
            flash.now.alert = 'This is awkward. You entered invalid login credentials - try again'
            render :new
        end
end

def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        current_user.orders << Order.new(is_active: true)
        flash[ :notice] = "you have successfully signed up"
        redirect_to root_path
    else
        render :new
    end

end

private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<h1> Cart </h1>

<% @carts.each do |cart| %>
    <%= form_tag("/remove_item/#{cart.id}") do %>
        <%= submit_tag "Remove", class: "btn btn-light" %>
        <%= Product.find(cart.product_id).artist_name %>
        <%= cart.quantity %>
    <% end %>
    <br>
    <%= form_tag("/purchase/active_order") do %>
        <%= submit_tag "Purchase", class: "btn btn-default" %>
    <% end %>
<% end %>

app/views/carts/purchase.html.erb
<h1> Throw It In The Bag </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Rozha+One" rel="stylesheet">
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
      <!-- Nav Bar below -->
        <nav class="navbar navbar-default">
          <div class="col-md-4">

          <%= link_to "CLASSICS", products_path, class: "navbar-brand" %>
          </div>
          <div class="col-md-4">

            <!-- User info -->
            <% if current_user %>
              Welcome, <%= current_user.name %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
            <% else %>
              <%= link_to 'Log In', login_path %>
              &nbsp;&nbsp;|&nbsp;&nbsp;
              <%= link_to 'Sign Up', new_user_path %>
            <% end %>
          </div>

          <div class="col-md-4">
          <!-- Product and Cart Buttons -->
            <div class="pull-right">
              <button class="btn btn-light"><%= link_to "Products", products_path %></button>
              <button class="btn btn-light"><%= link_to "Cart", carts_path %></button>
            </div>
          </div>
        </nav>
      </div>
      
          <%= yield %>
      
      </div>
    </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
        </ol>
        <div class="carousel-inner">
            <% @products.each_with_index do |product, idx| %>
                <div class="item <%= idx == 0 ? 'active' : '' %>">
                <!-- <h3><%#= product.artist_name %></h3> -->
                <!-- <h4><%#= product.album_name %></h4> -->
                    <%= image_tag product.album_url1 %>
                    <%= link_to "Show Me More", product_path(product.id) %>
                </div>
            <% end %>
            </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>

app/views/products/show.html.erb
    Artist: &nbsp;<%= @product.artist_name %><br>
    Album: &nbsp;<%= @product.album_name %><br>
    Price: &nbsp;<%= @product.price %><br>
    Description: &nbsp;<%= @product.description %>

<div class="product-images">
    <img src="<%= @product.album_url1 %>">
    <img src="<%= @product.album_url2 %>">
    <img src="<%= @product.album_url3 %>">
</div>

   

<%= flash[:notice] %>
<%= form_tag("/add_item/#{@product.id}") do %>
   <p class="text-white">Quantity &nbsp; <%= select_tag "quantity", options_for_select((1..10).map{|x| [x.to_s, x]}), :class => "btn btn-primary dropdown-toggle" %>
    <%= submit_tag("Add to Cart", :class => "btn btn-primary") %></p>
<% end %>
    </div>

app/views/users/new.html.erb
<h1> Users</h1>
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>